global class ActivationExternalPlatform {
	global ConnectApi.ActivationExternalPlatformAttributeConfig attributeConfig;
	global ConnectApi.ActivationPlatformCreationType creationType;
	global String keyPrefixName;
	global ConnectApi.ActivationPlatformPrivacyType privacyType;
	global ConnectApi.ActivationPlatformStatus status;
	global ConnectApi.ActivationPlatformType type;
	global ActivationExternalPlatform() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}