global class ActionPlanTemplateItemOutput {
	global String actionPlanTemplateVersion;
	global ConnectApi.ActionPlanTemplateItemsOutput dependencyItems;
	global Integer displayOrder;
	global String id;
	global Boolean isRequired;
	global String itemEntityType;
	global String name;
	global ActionPlanTemplateItemOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}