global class ActionPlanTemplateItemTaskInput {
	global String assignedTo;
	global String comment;
	global Datetime dueDate;
	global String id;
	global Boolean isRequired;
	global String priority;
	global String status;
	global String subject;
	global ActionPlanTemplateItemTaskInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}