global class ActionPlanTemplateUpdateOutputRepresentation {
	global String actionPlanTemplateVersionId;
	global List<ConnectApi.ActionPlanTemplateUpdateErrorOutputRepresentation> errors;
	global String message;
	global String status;
	global ActionPlanTemplateUpdateOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}