global class ActionPlanUpdateOutputRepresentation {
	global String actionPlanId;
	global List<ConnectApi.ActionPlanUpdateErrorOutputRepresentation> errors;
	global String message;
	global String status;
	global ActionPlanUpdateOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}