global class AdSpaceInputRepresentation {
	global List<ConnectApi.ObjectFieldInputRepresentation> adSpaceDimensions;
	global Map<String,ConnectApi.MapValueInputRepresentation> filter;
	global Integer offset;
	global Integer pageSize;
	global String productGroupType;
	global String productGroupTypeValue;
	global AdSpaceInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}