global class AiPlannerVoiceDefInput {
	global String developerName;
	global String id;
	global Boolean inboundFillerWordsBool;
	global String inboundKeywords;
	global String inboundModel;
	global String label;
	global String languageCode;
	global String outboundFillerSentences;
	global String outboundModel;
	global Double outboundSimilarity;
	global Double outboundSpeedNum;
	global Double outboundStability;
	global Double outboundStyleExaggeration;
	global String outboundVoice;
	global String plannerId;
	global String pronunciationDict;
	global AiPlannerVoiceDefInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}