global class AppointmentAttendee {
	global String attendeeId;
	global String attendeeType;
	global String email;
	global Boolean hasAttended;
	global String serviceAppointmentAttendeeId;
	global String serviceAppointmentId;
	global String status;
	global AppointmentAttendee() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}