global class AttributeLimitingExpressionInput {
	global String attributeName;
	global String entityName;
	global ConnectApi.FilterSortOrder order;
	global List<ConnectApi.QueryPathInputConfig> queryPathConfig;
	global String type;
	global AttributeLimitingExpressionInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}