global class AttributeLimitingExpressionRepresentation {
	global String attributeName;
	global String entityName;
	global ConnectApi.FilterSortOrder order;
	global ConnectApi.QueryPathConfigList queryPathConfig;
	global String type;
	global AttributeLimitingExpressionRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}