global class CalculateAdjustmentsRepresentation {
	global Double adjustedAmount;
	global String adjustmentReason;
	global List<ConnectApi.ClaimCovPaymentAdjDetailsRep> claimCovPaymentAdjustments;
	global List<ConnectApi.ErrorDetail> errors;
	global List<ConnectApi.InsPolicyLimitTrackingDetailsRep> insPolicyLimitTrackings;
	global Boolean isSuccess;
	global CalculateAdjustmentsRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}