global class CalculateAdjustmentsOutputRep {
	global Double adjustedAmount;
	global String adjustmentReason;
	global List<ConnectApi.ClaimCovPaymentAdjDetailsNode> claimCovPaymentAdjustments;
	global List<ConnectApi.InsPlcyLmtTrackingDetailsNode> insPolicyLimitTrackings;
	global CalculateAdjustmentsOutputRep() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}