global class CdpCalculatedInsightInput {
	global String apiName;
	global Boolean createdFromPackage;
	global String dataSpaceName;
	global ConnectApi.CalculatedInsightDefinitionTypeEnum definitionType;
	global String description;
	global String displayName;
	global Boolean draft;
	global String expression;
	global ConnectApi.CalcInsightHistoryPublishScheduleInterval historyPublishScheduleInterval;
	global String historyPublishTime;
	global String packagedCalculatedInsightApiName;
	global String publishScheduleEndDate;
	global ConnectApi.CalculatedInsightPublishScheduleInterval publishScheduleInterval;
	global String publishScheduleStartDateTime;
	global String sourceDeveloperName;
	global CdpCalculatedInsightInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}