global class CdpChatResponseOutputRep {
	global Map<String,String> additionalContextOutput;
	global String artifactId;
	global Map<String,Object> chart;
	global String chatUuid;
	global String currentStep;
	global String dataspaceName;
	global Object debugInfo;
	global String generatedSql;
	global String llmResponseWithReasoning;
	global Map<String,Object> queryData;
	global Map<String,Object> queryInfo;
	global String researchPlan;
	global String response;
	global String sessionTitle;
	global String status;
	global String tables;
	global CdpChatResponseOutputRep() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}