global class CdpLineageOutput {
	global String dataSpaceName;
	global ConnectApi.CdpCatalogGenreEnum2 genre;
	global String id;
	global String label;
	global Datetime lastModifiedDate;
	global String name;
	global List<String> tags;
	global String type;
	global CdpLineageOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}