global class CdpOptimizationOutputDataRepresentation {
	global String cdpDataLakeObject;
	global String cdpDataSpace;
	global String description;
	global List<ConnectApi.CdpOptimizationFieldAttributeOutputRepresentation> fields;
	global String name;
	global CdpOptimizationOutputDataRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}