global class CdpOptimizationFieldAttributeOutputRepresentation {
	global Boolean keyField;
	global Integer maxSize;
	global String name;
	global ConnectApi.CdpOptimizationFieldTypeEnum type;
	global CdpOptimizationFieldAttributeOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}