global class CdpOptimizationSourceDataInputRepresentation {
	global List<ConnectApi.CdpOptimizationAdditionalFieldAttributeRepresentation> additionalFieldAttributes;
	global List<ConnectApi.CdpDataModelObjectRepresentation> cdpDataModelObjects;
	global String cdpDataSpace;
	global List<ConnectApi.CdpOptimizationColumnInputRepresentation> columns;
	global List<ConnectApi.CdpOptimizationConditionInputRepresentation> dataFilters;
	global String description;
	global List<ConnectApi.CdpOptimizationFieldAttributeRepresentation> fields;
	global String name;
	global CdpOptimizationSourceDataInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}