global class CdpOptimizationVariableInputRepresentation {
	global String description;
	global String name;
	global String outputFieldName;
	global List<ConnectApi.CdpOptimizationVariableValueInputRepresentation> values;
	global ConnectApi.CdpOptimizationFieldTypeEnum variableType;
	global CdpOptimizationVariableInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}