global class CdpOptimizationObjectiveOutputRepresentation {
	global String description;
	global String formula;
	global List<ConnectApi.CdpOptimizationConditionFormulaRepresentation> formulaFields;
	global String name;
	global String outputFieldName;
	global ConnectApi.CdpOptimizationObjectiveEnum type;
	global CdpOptimizationObjectiveOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}