global class CdpOptimizationDataModelObjectRepresentation {
	global String description;
	global ConnectApi.CdpDataFieldCollectionRepresentation fields;
	global String id;
	global String label;
	global String name;
	global String namespace;
	global CdpOptimizationDataModelObjectRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}