global class CdpOptimizationAdditionalFieldAttributeOutputRepresentation {
	global List<ConnectApi.CdpOptimizationAdditionalFieldJoinAttributeOutputRepresentation> joins;
	global String name;
	global String source;
	global CdpOptimizationAdditionalFieldAttributeOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}