global class CdpOptimizationAdditionalFieldJoinAttributeRepresentation {
	global List<ConnectApi.CdpOptimizationAdditionalFieldJoinFieldRepresentation> fields;
	global String left;
	global ConnectApi.CdpOptimizationJoinOperatorEnum operator;
	global String right;
	global ConnectApi.CdpOptimizationJoinTypeEnum type;
	global CdpOptimizationAdditionalFieldJoinAttributeRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}