global class CdpOptimizationSyntaxValidationInputRepresentation {
	global String formula;
	global ConnectApi.CdpOptimizationFieldTypeEnum formulaReturnDataType;
	global List<ConnectApi.CdpOptimizationRecordColumnRepresentation> recordColumns;
	global List<ConnectApi.CdpOptimizationRecordTestColumnRepresentation> recordTestColumns;
	global CdpOptimizationSyntaxValidationInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}