global class CdpOptimizationAdditionalFieldJoinAttributeOutputRepresentation {
	global List<ConnectApi.CdpOptimizationAdditionalFieldJoinFieldOutputRepresentation> fields;
	global String left;
	global ConnectApi.CdpOptimizationJoinOperatorEnum operator;
	global String right;
	global ConnectApi.CdpOptimizationJoinTypeEnum type;
	global CdpOptimizationAdditionalFieldJoinAttributeOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}