global class CdpOptimizationOutputDataInputRepresentation {
	global String cdpDataLakeObject;
	global String cdpDataSpace;
	global String description;
	global List<ConnectApi.CdpOptimizationFieldAttributeRepresentation> fields;
	global String name;
	global CdpOptimizationOutputDataInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}