global class CdpOptimizationDataLakeObjectRepresentation {
	global String description;
	global ConnectApi.CdpDataLakeFieldCollectionRepresentation fields;
	global String id;
	global String label;
	global String name;
	global String namespace;
	global CdpOptimizationDataLakeObjectRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}