global class CdpOptimizationJobStatusOutputRepresentation {
	global String additionalInfo;
	global String dpcTaskId;
	global String errorMessage;
	global String jobRunId;
	global ConnectApi.CdpOptimizationJobStatusEnum status;
	global CdpOptimizationJobStatusOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}