global class CdpOptimizationDataModelObjectCollectionRepresentation {
	global List<ConnectApi.CdpOptimizationDataModelObjectRepresentation> optimizationDataModelObjects;
	global CdpOptimizationDataModelObjectCollectionRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}