global class CdpOptimizationAdditionalFieldAttributeRepresentation {
	global List<ConnectApi.CdpOptimizationAdditionalFieldJoinAttributeRepresentation> joins;
	global String name;
	global String source;
	global CdpOptimizationAdditionalFieldAttributeRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}