global class CdpOptimizationDataLakeObjectCollectionRepresentation {
	global List<ConnectApi.CdpOptimizationDataLakeObjectRepresentation> optimizationDataLakeObjects;
	global CdpOptimizationDataLakeObjectCollectionRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}