global class ChangeOrderItemAdjustmentLineSummaryInputRepresentation {
	global String changeType;
	global SObject orderItemAdjustmentLineSummary;
	global String orderItemSummaryId;
	global String referenceId;
	global ChangeOrderItemAdjustmentLineSummaryInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}