global class CheckListEvaluationResult {
	global String complaintStatus;
	global String groupId;
	global String groupName;
	global Double infoRuleCount;
	global List<ConnectApi.RulesEvaluationResult> ruleEvaluationResult;
	global CheckListEvaluationResult() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}