global class ChildrenCartItemCollection {
	global List<ConnectApi.CartItemResult> childCartItems;
	global Integer count;
	global String currentPageToken;
	global String currentPageUrl;
	global Boolean hasErrors;
	global String nextPageToken;
	global String nextPageUrl;
	global String previousPageToken;
	global String previousPageUrl;
	global ChildrenCartItemCollection() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}