global class ClaimItemDetailOutputRep {
	global ConnectApi.ClaimAttributeOutputs attributes;
	global String participantInstanceKey;
	global ConnectApi.ClaimItemRelatedObjectOutputs relatedObjects;
	global ClaimItemDetailOutputRep() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}