global class CloudProviderDetailsRepresentation {
	global String dataCloudDnsName;
	global String dataCloudVpceId;
	global ConnectApi.PrivateNetworkRouteStatus status;
	global ConnectApi.CloudProviderType type;
	global CloudProviderDetailsRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}