global class CoexistenceRecordReconciliationOutputRepresentation {
	global ConnectApi.ErrorOutputRepresentation error;
	global List<ConnectApi.ReconciliationResultOutputRepresentation> results;
	global CoexistenceRecordReconciliationOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}