global class Commerce360Consent {
	global String cdpTenantId;
	global String consentEndpointUrl;
	global String emailChannelTypeId;
	global String smsChannelTypeId;
	global ConnectApi.C360StatusRepresentation status;
	global String whatsAppChannelTypeId;
	global Commerce360Consent() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}