global class CommerceQuoteWithProductDetail {
	global Map<String,ConnectApi.RecordField> fields;
	global String id;
	global List<ConnectApi.BuyerProductSummary> products;
	global String quoteNumber;
	global String status;
	global CommerceQuoteWithProductDetail() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}