global class CommerceProductDynamicAttribute {
	global String displayValue;
	global String name;
	global String type;
	global ConnectApi.UnitOfMeasure unitOfMeasure;
	global String value;
	global CommerceProductDynamicAttribute() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}