global class ConsentSubscriptionItem {
	global ConnectApi.ConsentChannelType channelType;
	global ConnectApi.ConsentStatus consent;
	global String consentStatusDetails;
	global String contactPointValue;
	global String csId;
	global String csName;
	global String csctId;
	global ConsentSubscriptionItem() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}