global class ContextJSONOutputRepresentation {
	global List<ConnectApi.InsuranceSTOutputRepresentation> salesTransactions;
	global ContextJSONOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global List<ConnectApi.InsuranceSTOutputRepresentation> getSalesTransactions() { }
	global Integer hashCode() { }
	global void setSalesTransactions(List<ConnectApi.InsuranceSTOutputRepresentation> value) { }
	global String toString() { }

}