global class CPQPromotionOutputRepresentation {
	global String couponCode;
	global String description;
	global String displayName;
	global String endDateTime;
	global String id;
	global Boolean isAutomatic;
	global Boolean isCategoryPromo;
	global Boolean isProductPromo;
	global String name;
	global Integer priority;
	global String startDateTime;
	global String termsAndConditions;
	global CPQPromotionOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}