global class CreateProductRequestInputRepresentation {
	global String destinationLocation;
	global String product;
	global Double quantity;
	global String sourceLocation;
	global Boolean updateExistingProductRequest;
	global CreateProductRequestInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}