global class CreateClaimCvrPymtDtlOutputRep {
	global Double adjustedAmount;
	global String adjustedReason;
	global List<String> insurancePolicyLimitTrackingIds;
	global String paymentDetailId;
	global CreateClaimCvrPymtDtlOutputRep() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}