global class CreateClaimCvrPymtDtlInputRep {
	global List<ConnectApi.ClaimAdditionalFieldInputRep> additionalFields;
	global Double adjustedAmount;
	global String benefitName;
	global String claimCoverageId;
	global String claimId;
	global Double claimedAmount;
	global String coveragePaymentType;
	global String description;
	global Integer limitUnitCount;
	global String recipientId;
	global CreateClaimCvrPymtDtlInputRep() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}