global class CreateProductRequestsOutputRepresentation {
	global String errorCode;
	global String errorMessage;
	global String httpStatusCode;
	global Boolean isSuccess;
	global List<String> productRequestLineItemIds;
	global CreateProductRequestsOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}