global class CreateClaimCovPaymentDetailInputRep {
	global Object additionalFields;
	global Double adjustedAmount;
	global String benefitName;
	global Double claimedAmount;
	global String coveragePaymentType;
	global String description;
	global Integer limitUnitCount;
	global String recipientId;
	global CreateClaimCovPaymentDetailInputRep() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}