global class CustomerMergeListWithStatus {
	global List<String> accepted;
	global String code;
	global String jobId;
	global String message;
	global List<ConnectApi.RejectedCustomerMergeAccount> rejected;
	global Boolean success;
	global CustomerMergeListWithStatus() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}