global class DataCleanRoomCollaboration {
	global String apiKey;
	global String dataSpaceName;
	global String description;
	global List<ConnectApi.DataCleanRoomMember> members;
	global ConnectApi.DataCleanRoomStatusEnum status;
	global ConnectApi.DataCleanRoomTemplate templateVersion;
	global DataCleanRoomCollaboration() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}