global class DataOrgFeatureAllowListRepresentation {
	global String description;
	global ConnectApi.FeatureNameEnum featureName;
	global String orgId;
	global List<ConnectApi.DataOrgFeatureAllowListParamRepresentation> parameters;
	global DataOrgFeatureAllowListRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}