global class DataCleanRoomTemplate {
	global ConnectApi.UseCaseTemplateConfigRepresentation configuration;
	global String description;
	global String providerId;
	global Map<String,Object> queryTemplate;
	global ConnectApi.DataCleanRoomTemplateTypeEnum templateType;
	global String templateVersion;
	global ConnectApi.DataCleanRoomTemplateEnum useCaseType;
	global DataCleanRoomTemplate() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}