global class DataCleanRoomMember {
	global String invitationId;
	global ConnectApi.DataCleanRoomInvitationStatusEnum invitationStatus;
	global String memberId;
	global String memberOrgId;
	global ConnectApi.DataCleanRoomMemberStatusEnum memberStatus;
	global ConnectApi.DataCleanRoomMemberTypeEnum memberType;
	global String providerId;
	global String specificationId;
	global DataCleanRoomMember() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}