global class DataLakeDataSource {
	global List<ConnectApi.DirectoryAndFilesRepresentation> directoryAndFilesDetails;
	global Map<String,Object> sourceConfig;
	global String sourceId;
	global ConnectApi.DataLakeDataSourceTypeEnum sourceType;
	global DataLakeDataSource() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}