global class DataKitDeployBundleConfigAccountEngagement {
	global List<ConnectApi.DataSpaceFilterConditionApiConfig> dataSpaceFilterCriteriaApiConfig;
	global ConnectApi.AccountEngagementDataStreamTypeEnum dataStreamType;
	global String pardotTenantId;
	global DataKitDeployBundleConfigAccountEngagement() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}