global class DecisionTableCellLevelValidationOutputRepresentation {
	global Boolean isRowCriteriaValid;
	global List<String> validationErrors;
	global String validationSummary;
	global DecisionTableCellLevelValidationOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}