global class DocumentDetailsOutputRepresentation {
	global String documentEntityId;
	global String documentGenerationProcessId;
	global String documentTemplateId;
	global String documentTitle;
	global String existingDocumentId;
	global String recordId;
	global DocumentDetailsOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}