global class EditClaimCvrPymtDtlInputRep {
	global List<ConnectApi.ClaimAdditionalFieldInputRep> additionalFields;
	global Double adjustedAmount;
	global String claimCoverageId;
	global String claimCoveragePaymentDetailId;
	global String claimId;
	global Double claimedAmount;
	global String description;
	global Integer limitUnitCount;
	global String name;
	global String recipientId;
	global String status;
	global EditClaimCvrPymtDtlInputRep() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}