global class EditClaimCvrPaymentDetailInputRep {
	global Object additionalFields;
	global Double adjustedAmount;
	global Double claimedAmount;
	global String description;
	global Integer limitUnitCount;
	global String name;
	global String recipientId;
	global String status;
	global EditClaimCvrPaymentDetailInputRep() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}