global class EditClaimCvrPymtDtlOutputRep {
	global Double adjustedAmount;
	global String adjustedReason;
	global List<ConnectApi.ErrorDetail> errors;
	global List<String> insurancePolicyLimitTrackingIds;
	global Boolean isSuccess;
	global EditClaimCvrPymtDtlOutputRep() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}