global class EinsteinPromptTemplateDataProviderTypeConfigOutput {
	global String description;
	global String groupName;
	global String icon;
	global Boolean isTopLevel;
	global String label;
	global String parentNode;
	global Object scope;
	global EinsteinPromptTemplateDataProviderTypeConfigOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}