global class EinsteinPromptTemplateRepresentation {
	global ConnectApi.WrappedMapObject additionalData;
	global List<String> errorMessages;
	global Boolean hasWarning;
	global Boolean isSuccessful;
	global String statusCode;
	global String templateId;
	global String templateType;
	global String versionId;
	global List<String> warningMessages;
	global EinsteinPromptTemplateRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}