global class EinsteinPromptTypeSchemaRepresentation {
	global Boolean allowInputExtension;
	global List<ConnectApi.EinsteinPromptTypeSchemaInputFieldRepresentation> inputs;
	global String primaryObjectId;
	global EinsteinPromptTypeSchemaRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}