global class EinsteinPromptTypeRecordRepresentation {
	global List<String> excludedGlobalVariables;
	global ConnectApi.EinsteinPromptTypeSchemaRepresentation schema;
	global String templateTypeName;
	global EinsteinPromptTypeRecordRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}