global class EinsteinPromptTemplateExternalReferenceRepresentation {
	global String referenceId;
	global String referenceLocation;
	global String referenceName;
	global String referenceType;
	global EinsteinPromptTemplateExternalReferenceRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}