global class EinsteinPromptTypeSchemaInputFieldRepresentation {
	global String apiName;
	global String label;
	global String referenceName;
	global String typeDefinition;
	global EinsteinPromptTypeSchemaInputFieldRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}