global class EinsteinPromptTemplateAttachment {
	global ConnectApi.EinsteinPromptTemplateAttachmentExclusionInfo exclusionInfo;
	global String fileExtension;
	global String id;
	global String latestPublishedVersion;
	global String parentName;
	global String title;
	global EinsteinPromptTemplateAttachment() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}