global class ElementParallelizationOutputRepresentation {
	global Boolean elementParallelizationEnabled;
	global String pricingProcedureVersionId;
	global List<ConnectApi.TasksDto> tasks;
	global ElementParallelizationOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}