global class EligiblePlanDetailsOutputRepresentation {
	global List<ConnectApi.InsuranceMessageOutputRepresentation> messages;
	global List<ConnectApi.InsuranceGroupPlanOutputRepresentation> plans;
	global EligiblePlanDetailsOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}