global class EventBudgetRepresentation {
	global Double allocatedAmount;
	global String budgetId;
	global String createdById;
	global Datetime createdDate;
	global String id;
	global String lastModifiedById;
	global Datetime lastModifiedDate;
	global String mngEventId;
	global String name;
	global EventBudgetRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}