global class EventSubjectRepresentation {
	global String assignmentId;
	global String createdById;
	global Datetime createdDate;
	global String id;
	global String lastModifiedById;
	global Datetime lastModifiedDate;
	global String name;
	global String subjectId;
	global EventSubjectRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}