global class EventProductRepresentation {
	global Map<String,String> additionalFields;
	global String description;
	global String family;
	global String id;
	global String name;
	global String productCode;
	global EventProductRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}