global class EventTerritoryRepresentation {
	global Map<String,String> additionalFields;
	global String createdById;
	global Datetime createdDate;
	global String id;
	global String lastModifiedById;
	global Datetime lastModifiedDate;
	global String mngEventId;
	global String name;
	global ConnectApi.TerritoryRepresentation territory;
	global String territoryId;
	global EventTerritoryRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}