global class EventComplianceEvaluationResponse {
	global String checklistObject;
	global Datetime evaluatedAt;
	global String overallStatus;
	global List<ConnectApi.CheckListEvaluationResult> validationGroups;
	global EventComplianceEvaluationResponse() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}