global class ExternalPlatformConnectorRepresentation {
	global ConnectApi.ExternalPlatformFieldConfigRepresentation fieldConfig;
	global String keyPrefixName;
	global String name;
	global ExternalPlatformConnectorRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}