global class FulfillmentCriteriaGroupUpdateInputRepresentation {
	global List<ConnectApi.FulfillmentCriteriaInputRepresentation> criteria;
	global String description;
	global String externalReference;
	global Boolean isActive;
	global String state;
	global FulfillmentCriteriaGroupUpdateInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}