global class FulfillmentCriteriaGroupCreateInputRepresentation {
	global List<ConnectApi.FulfillmentCriteriaInputRepresentation> criteria;
	global String description;
	global String externalReference;
	global String name;
	global FulfillmentCriteriaGroupCreateInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}