global class GeneratedData {
	global String actionsSequence;
	global String citations;
	global String generatedResponse;
	global String invokedActions;
	global String outcome;
	global String sessionId;
	global String topic;
	global generatedData() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}