global class GetEvaluationStatusOutput {
	global Datetime endTime;
	global ConnectApi.EvaluationError errorRepresentation;
	global Datetime startTime;
	global ConnectApi.EvaluationStatus status;
	global GetEvaluationStatusOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}