global class GetEligibleClausesOutputRep {
	global List<ConnectApi.InsuranceProductClauseErrorRepresentation> errors;
	global List<ConnectApi.InsuranceProductClauseRepresentation> insuranceProductClauses;
	global Boolean success;
	global GetEligibleClausesOutputRep() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global List<ConnectApi.InsuranceProductClauseErrorRepresentation> getErrors() { }
	global List<ConnectApi.InsuranceProductClauseRepresentation> getInsuranceProductClauses() { }
	global Boolean getSuccess() { }
	global Integer hashCode() { }
	global void setErrors(List<ConnectApi.InsuranceProductClauseErrorRepresentation> value) { }
	global void setInsuranceProductClauses(List<ConnectApi.InsuranceProductClauseRepresentation> value) { }
	global void setSuccess(Boolean value) { }
	global String toString() { }

}