global class GetImagesForTinyMceListOutputRepresentation {
	global List<ConnectApi.GetImagesForTinyMceOutputRepresentation> images;
	global String orgDomain;
	global String orgId;
	global GetImagesForTinyMceListOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}