global class GetInventoryAllocationLocationDataRepresentation {
	global Double availableQuantity;
	global String locationId;
	global String locationName;
	global Double reservedQuantity;
	global GetInventoryAllocationLocationDataRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}