global class GetInventoryAllocationOutputRepresentation {
	global List<ConnectApi.GetInventoryAllocationLineItemDataRepresentation> allocationData;
	global String errorCode;
	global List<String> errorDetails;
	global String errorMessage;
	global Boolean isSuccess;
	global ConnectApi.PaginationMetaRepresentation meta;
	global GetInventoryAllocationOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}