global class GetInsPlcyCurrStndInputRep {
	global String claimCoverageId;
	global String claimId;
	global ConnectApi.IPLStandingCalcOptions options;
	global String policyAssetId;
	global String policyCoverageId;
	global String policyId;
	global String policyParticipantId;
	global String trackingDate;
	global GetInsPlcyCurrStndInputRep() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}