global class GroupCensusMemberInputRepresentation {
	global String accountId;
	global List<ConnectApi.AdditionalFieldsMapValue> additionalFields;
	global Double annualEligibleSalary;
	global String associationWithPrimaryMbr;
	global String birthdate;
	global String city;
	global String contactId;
	global String country;
	global Integer dependentCount;
	global String email;
	global String firstName;
	global Double fullTimeEquivalent;
	global String gender;
	global String groupCensusId;
	global String groupClassId;
	global String groupClassName;
	global String grpCensusGrpClassSummaryId;
	global String id;
	global Boolean isOptOutAllPlans;
	global Boolean isPortalUser;
	global String joinDate;
	global String lastname;
	global String memberKey;
	global String memberType;
	global String name;
	global String optOutPlanTypes;
	global String phoneNumber;
	global String policyStartDate;
	global String postalCode;
	global String primaryGroupCensusMemberId;
	global String primaryMemberCategory;
	global String primaryMemberSource;
	global String relationshipToPrimaryMember;
	global String smokerStatus;
	global String sourceSystemIdentifier;
	global String state;
	global String status;
	global String street;
	global GroupCensusMemberInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}