global class InnerEnsureFundsAsyncInputRepresentation {
	global String invoiceId;
	global Boolean isAllowPartial;
	global Boolean isReservedBalanceAmountConsidered;
	global String orderSummaryId;
	global List<ConnectApi.SequenceOrderPaymentSummaryInputRepresentation> sequences;
	global InnerEnsureFundsAsyncInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}