global class InsPolicyLmtCurrentStandingsInputRep {
	global String claimCoverageId;
	global String claimId;
	global ConnectApi.LimitStandingOptionInputRepresentation options;
	global String policyAssetId;
	global String policyCoverageId;
	global String policyId;
	global String policyParticipantId;
	global Datetime trackingDate;
	global InsPolicyLmtCurrentStandingsInputRep() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}