global class InsPolicyLimitTrackingDetailsRep {
	global String benefitName;
	global Double calcInitialAmount;
	global Integer calcInitialValue;
	global String category;
	global String policyLimitId;
	global Double postedAmount;
	global Integer postedValue;
	global Double remainingAmount;
	global Integer remainingValue;
	global String scope;
	global Double totalUsedAmount;
	global Integer totalUsedValue;
	global InsPolicyLimitTrackingDetailsRep() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}