global class InsPolicyLmtCalcStandingNode {
	global List<String> applicableActions;
	global String benefitName;
	global String category;
	global String claimCoverageId;
	global String claimId;
	global String durationType;
	global Double initialAmount;
	global Integer initialValue;
	global String itemType;
	global String parentMappedScopeId;
	global Double pendingAmount;
	global Integer pendingValue;
	global String policyAssetId;
	global String policyCoverageId;
	global String policyLimitId;
	global String policyLimitStandingKey;
	global String policyParticipantId;
	global Double predictedRemainingAmount;
	global Integer predictedRemainingValue;
	global String prodtAttrMappedScopeId;
	global Double remainingAmount;
	global Integer remainingValue;
	global String scope;
	global Double totalUsedAmount;
	global Integer totalUsedValue;
	global Datetime trackingEndDate;
	global Datetime trackingStartDate;
	global InsPolicyLmtCalcStandingNode() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}