global class InsPolicyLmtCalcStandingRepresentation {
	global List<ConnectApi.ErrorDetail> errors;
	global List<ConnectApi.InsPolicyLmtCalcStandingNode> insPolicyLmtCalcStandingNodes;
	global Boolean isSuccess;
	global InsPolicyLmtCalcStandingRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}