global class InsPlcyLmtTrackingDetailsNode {
	global ConnectApi.InsPolicyLimitTrackingAmounts amounts;
	global String benefitName;
	global String category;
	global String policyLimitId;
	global String scope;
	global ConnectApi.InsPolicyLimitTrackingValues values;
	global InsPlcyLmtTrackingDetailsNode() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}