global class InsuranceCreateProductClauseListOutputRepresentation {
	global List<ConnectApi.InsuranceProductClauseErrorRepresentation> errors;
	global Boolean isSuccess;
	global List<ConnectApi.InsuranceCreateProductClauseOutputRepresentation> productClauses;
	global InsuranceCreateProductClauseListOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global List<ConnectApi.InsuranceProductClauseErrorRepresentation> getErrors() { }
	global Boolean getIsSuccess() { }
	global List<ConnectApi.InsuranceCreateProductClauseOutputRepresentation> getProductClauses() { }
	global Integer hashCode() { }
	global void setErrors(List<ConnectApi.InsuranceProductClauseErrorRepresentation> value) { }
	global void setIsSuccess(Boolean value) { }
	global void setProductClauses(List<ConnectApi.InsuranceCreateProductClauseOutputRepresentation> value) { }
	global String toString() { }

}