global class InsuranceContributionRepresentation {
	global Double employeePremiumAmount;
	global Double employerPremiumAmount;
	global List<ConnectApi.InsuranceErrorRepresentation> errors;
	global String groupClassContributionId;
	global InsuranceContributionRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}