global class InsuranceClauseGenerationInputRepresentation {
	global String contextId;
	global List<ConnectApi.InstanceKeyInputRepresentation> instanceKeys;
	global ConnectApi.ClauseGenerationOptionsInputRepresentation options;
	global String quoteId;
	global List<String> quoteLineItemIds;
	global InsuranceClauseGenerationInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}