global class InsuranceCreateProductClauseOutputRepresentation {
	global String apiName;
	global String productClauseId;
	global InsuranceCreateProductClauseOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global String getApiName() { }
	global Double getBuildVersion() { }
	global String getProductClauseId() { }
	global Integer hashCode() { }
	global void setApiName(String value) { }
	global void setProductClauseId(String value) { }
	global String toString() { }

}