global class InsuranceProductClauseErrorRepresentation {
	global String code;
	global String message;
	global InsuranceProductClauseErrorRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global String getCode() { }
	global String getMessage() { }
	global Integer hashCode() { }
	global void setCode(String value) { }
	global void setMessage(String value) { }
	global String toString() { }

}