global class InsuranceAddEligibleProductClausesOutputRepresentation {
	global List<ConnectApi.InsuranceProductClauseErrorRepresentation> errors;
	global List<String> quoteLineItemInsProductClauseIds;
	global Boolean success;
	global InsuranceAddEligibleProductClausesOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global List<ConnectApi.InsuranceProductClauseErrorRepresentation> getErrors() { }
	global List<String> getQuoteLineItemInsProductClauseIds() { }
	global Boolean getSuccess() { }
	global Integer hashCode() { }
	global void setErrors(List<ConnectApi.InsuranceProductClauseErrorRepresentation> value) { }
	global void setQuoteLineItemInsProductClauseIds(List<String> value) { }
	global void setSuccess(Boolean value) { }
	global String toString() { }

}