global class InsuranceSTIOutputRepresentation {
	global List<ConnectApi.InsuranceSTIOutputRepresentation> childNodes;
	global Map<String,Object> fields;
	global List<ConnectApi.InsuranceSTIAOutputRepresentation> salesTransactionItemAttributes;
	global List<ConnectApi.InsuranceSTIClauseOutputRepresentation> salesTransactionItemClauses;
	global List<ConnectApi.InsuranceSTIROOutputRepresentation> salesTransactionItemRelatedObjects;
	global List<ConnectApi.InsuranceSTIRelationshipOutputRepresentation> salesTransactionItemRelationships;
	global List<ConnectApi.InsuranceSTITaxOutputRepresentation> salesTransactionItemTaxes;
	global InsuranceSTIOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global List<ConnectApi.InsuranceSTIOutputRepresentation> getChildNodes() { }
	global Map<String,Object> getFields() { }
	global List<ConnectApi.InsuranceSTIAOutputRepresentation> getSalesTransactionItemAttributes() { }
	global List<ConnectApi.InsuranceSTIClauseOutputRepresentation> getSalesTransactionItemClauses() { }
	global List<ConnectApi.InsuranceSTIROOutputRepresentation> getSalesTransactionItemRelatedObjects() { }
	global List<ConnectApi.InsuranceSTIRelationshipOutputRepresentation> getSalesTransactionItemRelationships() { }
	global List<ConnectApi.InsuranceSTITaxOutputRepresentation> getSalesTransactionItemTaxes() { }
	global Integer hashCode() { }
	global void setChildNodes(List<ConnectApi.InsuranceSTIOutputRepresentation> value) { }
	global void setFields(Map<String,Object> value) { }
	global void setSalesTransactionItemAttributes(List<ConnectApi.InsuranceSTIAOutputRepresentation> value) { }
	global void setSalesTransactionItemClauses(List<ConnectApi.InsuranceSTIClauseOutputRepresentation> value) { }
	global void setSalesTransactionItemRelatedObjects(List<ConnectApi.InsuranceSTIROOutputRepresentation> value) { }
	global void setSalesTransactionItemRelationships(List<ConnectApi.InsuranceSTIRelationshipOutputRepresentation> value) { }
	global void setSalesTransactionItemTaxes(List<ConnectApi.InsuranceSTITaxOutputRepresentation> value) { }
	global String toString() { }

}