global class InsuranceUpdateMemberPlansOutputRepresentation {
	global List<ConnectApi.InsuranceErrorRepresentation> errors;
	global List<String> failedPlans;
	global Boolean isSuccess;
	global String memberId;
	global List<String> updatedMemberPlans;
	global InsuranceUpdateMemberPlansOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}