global class InsuranceIndividualEnrollmentOutputRepresentation {
	global List<ConnectApi.ErrorResponseRepresentation> errors;
	global Boolean isSuccess;
	global List<ConnectApi.FamilyPolicyInfoOutputRepresentation> policies;
	global InsuranceIndividualEnrollmentOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}