global class InsuranceMemberAccountAndUserDetailsRepresentation {
	global String groupCensusId;
	global String groupCensusMemberId;
	global String personAccountId;
	global String userId;
	global InsuranceMemberAccountAndUserDetailsRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}