global class InsuranceUnderwritingRuleResultOutputRep {
	global Boolean isSuccess;
	global String ruleApiName;
	global InsuranceUnderwritingRuleResultOutputRep() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Boolean getIsSuccess() { }
	global String getRuleApiName() { }
	global Integer hashCode() { }
	global void setIsSuccess(Boolean value) { }
	global void setRuleApiName(String value) { }
	global String toString() { }

}