global class InsuranceAddEligibleProductClausesInputRepresentation {
	global String contextId;
	global List<String> instanceKey;
	global List<ConnectApi.InsuranceProductClauseInputRepresentation> insuranceProductClauses;
	global ConnectApi.InsuranceAddEligibleProductClausesOptionsInputRepresentation options;
	global String quoteId;
	global String quoteLineItemId;
	global InsuranceAddEligibleProductClausesInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}