global class InsuranceBulkCensusMgmtInputRepresentation {
	global Integer batchSize;
	global String contentDocumentId;
	global String contentDocumentVersionId;
	global Map<String,String> csvColumnMapping;
	global List<String> duplicateDetectionFields;
	global Boolean shouldExecuteConfigurationRule;
	global InsuranceBulkCensusMgmtInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}