global class InsuranceMemberContactAndUserDetailsRepresentation {
	global String contactId;
	global String groupCensusId;
	global String groupCensusMemberId;
	global String userId;
	global InsuranceMemberContactAndUserDetailsRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}