global class InsuranceContactsAndUsersCreationInputRepresentation {
	global Map<String,String> fieldMappings;
	global String groupCensusId;
	global List<String> groupCensusMemberIdList;
	global List<String> matchingKeyList;
	global ConnectApi.PortalUserCreationInputRepresentation userDetails;
	global InsuranceContactsAndUsersCreationInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}