global class InsuranceMemberRatingDetailsRepresentation {
	global List<ConnectApi.InsuranceErrorRepresentation> errors;
	global String memberId;
	global List<ConnectApi.InsurancePlanRatingRepresentation> plans;
	global InsuranceMemberRatingDetailsRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}