global class InsuranceMemberRatingRepresentation {
	global List<ConnectApi.InsuranceErrorRepresentation> errors;
	global String id;
	global List<ConnectApi.InsuranceMemberRatingDetailsRepresentation> pricingResults;
	global InsuranceMemberRatingRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}