global class InsuranceCensusSummarySyncOutputRepresentation {
	global List<ConnectApi.ErrorResponseRepresentation> errors;
	global ConnectApi.InsuranceGroupCensusOutputRepresentation groupCensus;
	global Boolean isSuccess;
	global InsuranceCensusSummarySyncOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}