global class InsuranceGroupPlanOutputRepresentation {
	global List<ConnectApi.InsuranceObjectMapRepresentation> attributes;
	global List<ConnectApi.InsuranceGroupPlanOutputRepresentation> coverages;
	global Boolean isOptional;
	global String planId;
	global String planName;
	global String productCategory;
	global InsuranceGroupPlanOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}