global class InsuranceProductClauseRepresentation {
	global String category;
	global String clauseName;
	global String description;
	global String effectiveDate;
	global String expirationDate;
	global String insuranceProductClauseId;
	global String type;
	global InsuranceProductClauseRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global String getCategory() { }
	global String getClauseName() { }
	global String getDescription() { }
	global String getEffectiveDate() { }
	global String getExpirationDate() { }
	global String getInsuranceProductClauseId() { }
	global String getType() { }
	global Integer hashCode() { }
	global void setCategory(String value) { }
	global void setClauseName(String value) { }
	global void setDescription(String value) { }
	global void setEffectiveDate(String value) { }
	global void setExpirationDate(String value) { }
	global void setInsuranceProductClauseId(String value) { }
	global void setType(String value) { }
	global String toString() { }

}