global class InsuranceCreateProductClauseInputRepresentation {
	global String apiName;
	global String effectiveDate;
	global String expirationDate;
	global String insuranceClauseId;
	global String name;
	global String productPath;
	global String productRelatedComponentId;
	global String rootProduct;
	global List<ConnectApi.InsuranceProductClauseVariableMappingInputRepresentation> variableMappings;
	global InsuranceCreateProductClauseInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}