global class InsuranceUpdateProductClauseOutputRepresentation {
	global List<ConnectApi.InsuranceProductClauseErrorRepresentation> errors;
	global Boolean isSuccess;
	global String productClauseId;
	global InsuranceUpdateProductClauseOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global List<ConnectApi.InsuranceProductClauseErrorRepresentation> getErrors() { }
	global Boolean getIsSuccess() { }
	global String getProductClauseId() { }
	global Integer hashCode() { }
	global void setErrors(List<ConnectApi.InsuranceProductClauseErrorRepresentation> value) { }
	global void setIsSuccess(Boolean value) { }
	global void setProductClauseId(String value) { }
	global String toString() { }

}