global class InsuranceContractCreationInputRepresentation {
	global List<ConnectApi.ContractItem> additionalFields;
	global String contractEndDate;
	global String contractStartDate;
	global Integer contractTerm;
	global String enrollmentEndDate;
	global String enrollmentStartDate;
	global String quoteId;
	global InsuranceContractCreationInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}