global class InsuranceSTOutputRepresentation {
	global List<ConnectApi.InsuranceAppUsageAssignmentOutputRepresentation> appUsageAssignments;
	global Map<String,Object> fields;
	global List<ConnectApi.InsuranceSTIOutputRepresentation> salesTransactionItems;
	global InsuranceSTOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global List<ConnectApi.InsuranceAppUsageAssignmentOutputRepresentation> getAppUsageAssignments() { }
	global Double getBuildVersion() { }
	global Map<String,Object> getFields() { }
	global List<ConnectApi.InsuranceSTIOutputRepresentation> getSalesTransactionItems() { }
	global Integer hashCode() { }
	global void setAppUsageAssignments(List<ConnectApi.InsuranceAppUsageAssignmentOutputRepresentation> value) { }
	global void setFields(Map<String,Object> value) { }
	global void setSalesTransactionItems(List<ConnectApi.InsuranceSTIOutputRepresentation> value) { }
	global String toString() { }

}