global class InsuranceAppUsageAssignmentOutputRepresentation {
	global Map<String,Object> fields;
	global InsuranceAppUsageAssignmentOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Map<String,Object> getFields() { }
	global Integer hashCode() { }
	global void setFields(Map<String,Object> value) { }
	global String toString() { }

}