global class InsuranceUpdateProductClauseInputRepresentation {
	global String effectiveDate;
	global String expirationDate;
	global List<ConnectApi.InsuranceProductClauseVariableMappingInputRepresentation> variableMappings;
	global InsuranceUpdateProductClauseInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}