global class InsuranceAddMemberPlansOutputRepresentation {
	global List<ConnectApi.InsuranceErrorRepresentation> errors;
	global Boolean isSuccess;
	global String memberId;
	global List<String> memberPlans;
	global InsuranceAddMemberPlansOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}