global class InsuranceGetMemberPlansOutputRepresentation {
	global ConnectApi.InsuranceErrorRepresentation error;
	global String memberId;
	global Map<String,ConnectApi.InsurancePlanListOutputRepresentation> plans;
	global InsuranceGetMemberPlansOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}