global class InsuranceClauseGenerationOutputRepresentation {
	global String asyncBulkRequestId;
	global List<ConnectApi.InsuranceProductClauseErrorRepresentation> errors;
	global Boolean success;
	global InsuranceClauseGenerationOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global String getAsyncBulkRequestId() { }
	global Double getBuildVersion() { }
	global List<ConnectApi.InsuranceProductClauseErrorRepresentation> getErrors() { }
	global Boolean getSuccess() { }
	global Integer hashCode() { }
	global void setAsyncBulkRequestId(String value) { }
	global void setErrors(List<ConnectApi.InsuranceProductClauseErrorRepresentation> value) { }
	global void setSuccess(Boolean value) { }
	global String toString() { }

}