global class InsuranceAccountsAndUsersCreationRepresentation {
	global List<ConnectApi.InsuranceMemberAccountAndUserDetailsRepresentation> accountsAndUsersDetails;
	global List<ConnectApi.InsuranceErrorRepresentation> errors;
	global String groupCensusId;
	global Boolean isSuccess;
	global InsuranceAccountsAndUsersCreationRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}