global class InsurancePlansEligibilityPatchInputRepresentation {
	global List<ConnectApi.InsuranceGroupPlanInputRepresentation> addedPlans;
	global String contextId;
	global List<ConnectApi.InsuranceGroupPlanInputRepresentation> deletedPlans;
	global InsurancePlansEligibilityPatchInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}