global class InsuranceContactsAndUsersCreationRepresentation {
	global List<ConnectApi.InsuranceMemberContactAndUserDetailsRepresentation> contactsAndUsersDetails;
	global List<ConnectApi.InsuranceErrorRepresentation> errors;
	global String groupCensusId;
	global Boolean isSuccess;
	global InsuranceContactsAndUsersCreationRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}