global class InvokeUnderwritingRuleOputRep {
	global String evaluationCriteria;
	global String fromStage;
	global Boolean isSuccess;
	global String objectId;
	global String objectName;
	global List<ConnectApi.InsuranceUnderwritingRuleResultOutputRep> ruleResult;
	global String stageTransitionName;
	global String stageTransitionUnderwritingEvaluationId;
	global String toStage;
	global InvokeUnderwritingRuleOputRep() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global String getEvaluationCriteria() { }
	global String getFromStage() { }
	global Boolean getIsSuccess() { }
	global String getObjectId() { }
	global String getObjectName() { }
	global List<ConnectApi.InsuranceUnderwritingRuleResultOutputRep> getRuleResult() { }
	global String getStageTransitionName() { }
	global String getStageTransitionUnderwritingEvaluationId() { }
	global String getToStage() { }
	global Integer hashCode() { }
	global void setEvaluationCriteria(String value) { }
	global void setFromStage(String value) { }
	global void setIsSuccess(Boolean value) { }
	global void setObjectId(String value) { }
	global void setObjectName(String value) { }
	global void setRuleResult(List<ConnectApi.InsuranceUnderwritingRuleResultOutputRep> value) { }
	global void setStageTransitionName(String value) { }
	global void setStageTransitionUnderwritingEvaluationId(String value) { }
	global void setToStage(String value) { }
	global String toString() { }

}