global class IPLStandingCalcCoverageInfo {
	global String benefitName;
	global String claimCoverageId;
	global String claimId;
	global String policyAssetId;
	global String policyCoverageId;
	global String policyParticipantId;
	global IPLStandingCalcCoverageInfo() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}