global class IPLStandingCalcOutputNode {
	global ConnectApi.IPLStandingCalcAmounts amounts;
	global ConnectApi.IPLStandingCalcCoverageInfo coverageInfo;
	global ConnectApi.IPLStandingCalcLimitAttributes limitAttributes;
	global ConnectApi.IPLStandingMappedScopes mappedScopes;
	global ConnectApi.IPLStandingTrackingDates trackingDates;
	global ConnectApi.IPLStandingCalcValues values;
	global IPLStandingCalcOutputNode() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}