global class IPLStandingCalcLimitAttributes {
	global List<String> applicableActions;
	global String category;
	global String durationType;
	global String itemType;
	global String policyLimitId;
	global String policyLimitStandingKey;
	global String scope;
	global IPLStandingCalcLimitAttributes() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}