global class IPLStandingCalcValues {
	global Integer initialValue;
	global Integer pendingValue;
	global Integer predictedRemainingValue;
	global Integer remainingValue;
	global Integer totalUsedValue;
	global IPLStandingCalcValues() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}