global class IPLStandingCalcAmounts {
	global Double initialAmount;
	global Double pendingAmount;
	global Double predictedRemainingAmount;
	global Double remainingAmount;
	global Double totalUsedAmount;
	global IPLStandingCalcAmounts() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}