global class KpiOutputRepresentation {
	global String displayValue;
	global String errorMessage;
	global Boolean hasError;
	global String kpiDescription;
	global String kpiId;
	global String kpiName;
	global String value;
	global KpiOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}