global class LayoutAssignmentOutputRepresentation {
	global String objectApiName;
	global String pageLayoutName;
	global List<String> profileNames;
	global List<String> recordTypeNames;
	global LayoutAssignmentOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}