global class LearningItemProgressOutputRepresentation {
	global Datetime completedDate;
	global Double completedPercent;
	global String id;
	global Boolean isCompleted;
	global String learningItemId;
	global LearningItemProgressOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}