global class LearningRuleOutput {
	global String description;
	global Boolean isFulfilled;
	global String learningId;
	global String learningRuleId;
	global String name;
	global String ruleId;
	global String ruleResultDetails;
	global Boolean ruleResultStatus;
	global String type;
	global LearningRuleOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}