global class LearningEquivalencyOutputItem {
	global List<ConnectApi.EducationCloudCustomFieldRepresentation> customAttributes;
	global Boolean isActive;
	global String learningEquivalencyId;
	global List<String> learningProgramIds;
	global String name;
	global ConnectApi.LearningsMappingRepresentation source;
	global List<ConnectApi.LearningsMappingRepresentation> target;
	global LearningEquivalencyOutputItem() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}