global class LearningItemOutputRepresentation {
	global Double completionRate;
	global String contentType;
	global String createdBy;
	global Datetime createdDate;
	global String description;
	global Integer duration;
	global Boolean hasAssignments;
	global String id;
	global String imageUrl;
	global String learningContentId;
	global String title;
	global String url;
	global LearningItemOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}