global class LearningItemListOutputRepresentation {
	global List<ConnectApi.LearningItemOutputRepresentation> items;
	global ConnectApi.LearningItemStatusOutputRepresentation status;
	global LearningItemListOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}