global class LearningItemProgressListOutputRepresentation {
	global List<ConnectApi.LearningItemProgressOutputRepresentation> items;
	global ConnectApi.ErrorResponseOutputRepresentation status;
	global LearningItemProgressListOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}