global class LearningDetailsRepresentation {
	global Double duration;
	global String durationUnit;
	global String learningId;
	global String minimumLetterGrade;
	global Double minimumNumericGrade;
	global String name;
	global String provider;
	global String referencedLearningId;
	global LearningDetailsRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}