global class LpPersonalizationItem {
	global Object attributes;
	global List<Object> data;
	global String decisionId;
	global List<ConnectApi.PersonalizationDiagnostic> diagnostics;
	global String personalizationId;
	global String personalizationPointId;
	global String personalizationPointName;
	global LpPersonalizationItem() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}