global class LSC4CE {
	global Object clone() { }
	global static ConnectApi.FilteredQualifiedProductsOutput filteredQualifiedProducts(String territoryId, ConnectApi.FilteredQualifiedProductsInput requestBody) { }
	global static ConnectApi.GenericSearchOutput genericSearch(ConnectApi.GenericSearchInput GenericSearchInput) { }
	global static ConnectApi.QualifiedProductsOutput qualifiedProducts(String territoryId, ConnectApi.QualifiedProductsInput requestBody) { }

}