global class ManagedContentProviderInstance {
	global String instanceKey;
	global Boolean isDefault;
	global Boolean isEnabledForSpace;
	global String name;
	global String providerInstanceId;
	global ManagedContentProviderInstance() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}