global class ManagedContentDocumentCollection {
	global List<ConnectApi.ManagedContentDocument> contents;
	global String currentPageUrl;
	global String nextPageUrl;
	global Integer total;
	global ManagedContentDocumentCollection() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}