global class ManagedEventInputRepresentation {
	global Map<String,String> additionalFields;
	global String campaignId;
	global String description;
	global Datetime endDateTime;
	global Integer estimatedParticipantCount;
	global String eventMode;
	global String eventStatus;
	global String eventUrl;
	global String locationId;
	global String mngEventTypeId;
	global String name;
	global Datetime startDateTime;
	global ManagedEventInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}