global class MarketingCloudConnector {
	global ConnectApi.BusinessUnitConfig businessUnitConfig;
	global Long enterpriseId;
	global String enterpriseName;
	global String name;
	global String targetSubType;
	global MarketingCloudConnector() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}