global class MatchingAccountsCollectionRep {
	global List<ConnectApi.MatchingAccountRep> accounts;
	global String errorMessage;
	global String jobPositionShiftId;
	global String locationIdCriteria;
	global List<String> qualificationIdsCriteria;
	global String timeRangeCriteria;
	global MatchingAccountsCollectionRep() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}