global class MediaConfigurationOutputRepresentation {
	global ConnectApi.MediaConfiguredDecisionTableOutputRepresentation configuredDecisionTableData;
	global List<Object> metadataDetails;
	global MediaConfigurationOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}