global class MediaProductConfiguratorOptionsInputRepresentation {
	global String pricingProcedure;
	global Boolean shouldAddDefaultConfiguration;
	global Boolean shouldExecuteConfigurationRules;
	global Boolean shouldExecutePricing;
	global Boolean shouldQualifyAllProductsInTransaction;
	global Boolean shouldReturnProductCatalogData;
	global Boolean shouldValidateAmendRenewCancel;
	global Boolean shouldValidateProductCatalog;
	global MediaProductConfiguratorOptionsInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}