global class MediaProductConfigurationOutputRepresentation {
	global List<Object> catalogProducts;
	global List<Object> errors;
	global Boolean isSuccess;
	global Map<String,Object> messages;
	global Map<String,Object> transactionContext;
	global String transactionContextId;
	global String transactionContextMappingId;
	global Map<String,Object> transactionQualification;
	global List<Object> uiTreatments;
	global MediaProductConfigurationOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}