global class MediaConfigurationMetadataOutputRepresentation {
	global ConnectApi.MediaConfigurationOutputRepresentation configurationDetails;
	global List<ConnectApi.MediaConfigurationErrorOutputRepresentation> errorList;
	global Boolean isSuccess;
	global MediaConfigurationMetadataOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}