global class MetadataActionResult {
	global String actionTarget;
	global String apiName;
	global String associatedEntityId;
	global String errorMessage;
	global Boolean hasError;
	global String id;
	global String label;
	global MetadataActionResult() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}