global class MlRetrieverQueryResultRepresentation {
	global ConnectApi.MlRetrieverExecutionDetailsRepresentation executionDetails;
	global List<ConnectApi.MlRetrieverQueryResultDocumentRepresentation> searchResults;
	global MlRetrieverQueryResultRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}