global class MlRetrieverExecutionStepRepresentation {
	global String description;
	global Integer duration;
	global String label;
	global ConnectApi.MlRetrieverExecutionStepTypeEnum type;
	global MlRetrieverExecutionStepRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}