global class MlRetrieverExecutionDetailsRepresentation {
	global List<ConnectApi.MlRetrieverExecutionStepRepresentation> executionSteps;
	global ConnectApi.MlRetrieverExecutionSummaryRepresentation executionSummary;
	global List<String> sourceObjectRecordIds;
	global MlRetrieverExecutionDetailsRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}