global class MngEventBudgetUpdateInputRepresentation {
	global Map<String,String> additionalFields;
	global Double allocatedAmount;
	global String name;
	global Double totalActualExpenseAmount;
	global Double totalEstimatedExpenseAmount;
	global MngEventBudgetUpdateInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}