global class MngEventCollectionRepresentation {
	global String errorCode;
	global Boolean isSuccess;
	global String message;
	global List<ConnectApi.ManagedEventRepresentation> response;
	global MngEventCollectionRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}