global class MngEventParticipantCollection {
	global String errorCode;
	global Boolean isSuccess;
	global String message;
	global List<ConnectApi.ManagedEventParticipantRepresentation> response;
	global MngEventParticipantCollection() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}