global class MngEventParticipantUpdateInput {
	global Map<String,String> additionalFields;
	global String attendanceConsent;
	global Datetime attendanceConsentDateTime;
	global String attendanceMode;
	global String attendanceStatus;
	global String comments;
	global Integer currentInvitationCount;
	global Boolean doesRequireMeal;
	global String invitationCntDiscrepancyRsn;
	global String invitationConsent;
	global Datetime invitationConsentDateTime;
	global Integer invitationQuota;
	global Datetime invitationSentDateTime;
	global String invitedById;
	global Boolean isInvitationSent;
	global String mealType;
	global String name;
	global String participantPartyRecileStatus;
	global String participantResponse;
	global String participantRole;
	global String participantType;
	global String primaryHealthcareProviderId;
	global MngEventParticipantUpdateInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}