global class MultipleFulfillmentOrderInvoicesOutputRepresentation {
	global List<String> invoiceIds;
	global Map<String,ConnectApi.FulfillmentOrderInvoiceOutputRepresentation> invoicesMap;
	global MultipleFulfillmentOrderInvoicesOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}