global class ObjectSourceTargetMapRepresentation {
	global String developerName;
	global List<ConnectApi.FieldSourceTargetMapRepresentation> fieldMappings;
	global String sourceEntityDeveloperName;
	global ConnectApi.ObjectMappingStatus status;
	global String targetEntityDeveloperName;
	global ObjectSourceTargetMapRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}