global class OnDemandDocGenOutputRepresentation {
	global ConnectApi.DocumentDetailsOutputRepresentation details;
	global List<ConnectApi.ErrorResponse> errors;
	global Boolean isSuccess;
	global String requestIdentifier;
	global OnDemandDocGenOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}