global class OutOfSequenceEndorsePolicyInputRepresentation {
	global String contextId;
	global String effectiveDate;
	global ConnectApi.AdditionalFieldsFieldSetInputRepresentation fieldSetIds;
	global ConnectApi.InsurancePolicyInputRepresentation insurancePolicy;
	global ConnectApi.InsurancePolicyTransactionInputRepresentation transactionRecord;
	global OutOfSequenceEndorsePolicyInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}