global class PayClaimCvrPymtDtlOutputRep {
	global String claimPaymentSummaryId;
	global Integer consumedLimitCount;
	global List<String> insPolicyLimitTrackingIds;
	global Boolean isSuccess;
	global Double paidAmount;
	global PayClaimCvrPymtDtlOutputRep() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}