global class PayExGratiaClaimCvrPymtDtlRep {
	global String claimPaymentSummaryId;
	global Integer consumedLimitCount;
	global Double exceededAmount;
	global Integer exceededCount;
	global List<String> insPolicyLimitTrackingIds;
	global Boolean isSuccess;
	global Double paidAmount;
	global PayExGratiaClaimCvrPymtDtlRep() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}