global class PicklistValueRepresentation {
	global ConnectApi.AbstractPicklistValueAttributesRepresentation attributes;
	global String label;
	global List<Integer> validFor;
	global String value;
	global PicklistValueRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}