global class PicklistValuesRepresentation {
	global Map<String,Integer> controllerValues;
	global ConnectApi.PicklistValueRepresentation defaultValue;
	global String url;
	global List<ConnectApi.PicklistValueRepresentation> values;
	global PicklistValuesRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}