global class PricingProcedureAttributeDto {
	global String attributeIOType;
	global String attributeName;
	global String attributeType;
	global Object attributeValue;
	global String contextPath;
	global String dataType;
	global String id;
	global Boolean isContextTag;
	global Boolean isFilterParam;
	global Boolean isFormalParam;
	global Boolean isFormula;
	global Boolean isRequiredParam;
	global Integer level;
	global String operator;
	global PricingProcedureAttributeDto() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}