global class ProductChild {
	global ConnectApi.ProductComponentGroup componentGroup;
	global String defaultQuantity;
	global Boolean isDefault;
	global Boolean isEntitled;
	global Boolean isPriceIncludedInParent;
	global Boolean isRequired;
	global ConnectApi.ProductDetail productInfo;
	global ProductChild() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}