global class ProductRequirementSpecificationVersionOutput {
	global String additionalInfo;
	global String assumptions;
	global String constraints;
	global String contentDocumentId;
	global String createdById;
	global String createdDate;
	global String customAttributes;
	global String effectiveDate;
	global String expiryDate;
	global String id;
	global String intendedUse;
	global String lastModifiedById;
	global String lastModifiedDate;
	global String name;
	global String ownerId;
	global List<ConnectApi.ProductRequirementSpecificationItemOutput> productRequirementSpecificationItems;
	global String productRqmtSpecId;
	global String purpose;
	global String refProductCategoryId;
	global String refProductId;
	global String scope;
	global String verificationMethod;
	global Integer version;
	global ProductRequirementSpecificationVersionOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}