global class ProductRequirementSpecificationItemOutput {
	global String acceptanceCriteria;
	global String additionalInfo;
	global String category;
	global String createdById;
	global String createdDate;
	global String customAttributes;
	global String id;
	global String lastModifiedById;
	global String lastModifiedDate;
	global String name;
	global String ownerId;
	global String productRqmtSpecVersionId;
	global String riskLevel;
	global String statement;
	global String targetValue;
	global String tolerance;
	global String unitOfMeasureId;
	global String verificationMethod;
	global ProductRequirementSpecificationItemOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}