global class ProductRequirementSpecificationErrorResponse {
	global List<ConnectApi.ProductRequirementSpecificationErrorDetail> details;
	global String message;
	global String requestUniqueId;
	global String status;
	global productRequirementSpecificationErrorResponse() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}