global class ProductRequirementSpecificationOutput {
	global String accountId;
	global String contactId;
	global String createdById;
	global String createdDate;
	global String customAttributes;
	global String id;
	global String lastModifiedById;
	global String lastModifiedDate;
	global String latestVersionId;
	global String name;
	global String origin;
	global String ownerId;
	global String priority;
	global List<ConnectApi.ProductRequirementSpecificationVersionOutput> productRequirementSpecificationVersions;
	global String stage;
	global String status;
	global ProductRequirementSpecificationOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}