global class PromptTemplateDataProviderInstanceConfigRepresentation {
	global String apiName;
	global Map<String,Object> dataProviderBundle;
	global ConnectApi.PromptTemplateDataProviderOutputParamRepresentation defaultOutputParam;
	global String definition;
	global String description;
	global String groupName;
	global List<ConnectApi.PromptTemplateDataProviderInputParamRepresentation> inputParams;
	global String label;
	global Map<String,String> mappedInputs;
	global String nodeIcon;
	global List<ConnectApi.PromptTemplateDataProviderOutputParamRepresentation> outputParams;
	global String referenceName;
	global String scopedToTarget;
	global String subGroup;
	global PromptTemplateDataProviderInstanceConfigRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}