global class PromptTemplateDataProviderConfigCollectionRepresentation {
	global List<ConnectApi.PromptTemplateDataProviderInstanceConfigRepresentation> dataProviderInstanceConfigs;
	global PromptTemplateDataProviderConfigCollectionRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}