global class PromptTemplateDataProviderTypeConfigCollectionOutput {
	global List<ConnectApi.EinsteinPromptTemplateDataProviderTypeConfigOutput> dataProviderTypeConfigs;
	global PromptTemplateDataProviderTypeConfigCollectionOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}