global class ProviderSearchCriteriaInputRep {
	global Boolean acceptingNewPatients;
	global Map<String,String> additionalSearchCriteria;
	global List<String> languagesSpoken;
	global String licenseJurisdictionCountry;
	global String licenseJurisdictionRegion;
	global String licenseJurisdictionState;
	global String nationalProviderIdentifier;
	global List<String> planTypes;
	global String providerGender;
	global String providerName;
	global String providerType;
	global List<String> specialties;
	global List<String> subSpecialties;
	global ProviderSearchCriteriaInputRep() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}