global class PublicGroupOutputRepresentation {
	global Boolean grantAccessUsingHierarchy;
	global String groupName;
	global String membershipLevel;
	global String name;
	global String url;
	global PublicGroupOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}