global class QuerySqlParameterItem {
	global ConnectApi.QuerySqlParameterItem innerElement;
	global Long length;
	global String name;
	global Integer precision;
	global Integer scale;
	global ConnectApi.TypeEnum type;
	global String value;
	global QuerySqlParameterItem() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}