global class RatingInputNodeOutputRepresentation {
	global Map<String,Object> additionalFields;
	global Map<String,Object> attributes;
	global List<String> instanceKeys;
	global String productCode;
	global RatingInputNodeOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Map<String,Object> getAdditionalFields() { }
	global Map<String,Object> getAttributes() { }
	global Double getBuildVersion() { }
	global List<String> getInstanceKeys() { }
	global String getProductCode() { }
	global Integer hashCode() { }
	global void setAdditionalFields(Map<String,Object> value) { }
	global void setAttributes(Map<String,Object> value) { }
	global void setInstanceKeys(List<String> value) { }
	global void setProductCode(String value) { }
	global String toString() { }

}