global class RatingOptionsOutputRepresentation {
	global Boolean executeConfigurationRules;
	global Boolean executePricing;
	global String pricingProcedure;
	global Boolean returnContextJSON;
	global Boolean returnProductDetails;
	global RatingOptionsOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Boolean getExecuteConfigurationRules() { }
	global Boolean getExecutePricing() { }
	global String getPricingProcedure() { }
	global Boolean getReturnContextJSON() { }
	global Boolean getReturnProductDetails() { }
	global Integer hashCode() { }
	global void setExecuteConfigurationRules(Boolean value) { }
	global void setExecutePricing(Boolean value) { }
	global void setPricingProcedure(String value) { }
	global void setReturnContextJSON(Boolean value) { }
	global void setReturnProductDetails(Boolean value) { }
	global String toString() { }

}