global class RatingResultOutputRepresentation {
	global List<ConnectApi.RatingResultOutputRepresentation> childNodes;
	global Map<String,Object> details;
	global RatingResultOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global List<ConnectApi.RatingResultOutputRepresentation> getChildNodes() { }
	global Map<String,Object> getDetails() { }
	global Integer hashCode() { }
	global void setChildNodes(List<ConnectApi.RatingResultOutputRepresentation> value) { }
	global void setDetails(Map<String,Object> value) { }
	global String toString() { }

}