global class ReadSalesTransactionContextRepresentation {
	global List<ConnectApi.PlaceSalesTransactionErrorResponse> errors;
	global Boolean isSuccess;
	global ConnectApi.ReadSalesTransactionRecordsRepresentation response;
	global ReadSalesTransactionContextRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}