global class RecordAndTargetingTemplateInputRepresentation {
	global List<ConnectApi.RecordInputRepresentation> recordDetails;
	global ConnectApi.ApplyTargetingMetadataInputRepresentation targetingTemplateDetails;
	global RecordAndTargetingTemplateInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}