global class RefundInstructionsHintInputRepresentation {
	global List<ConnectApi.PaymentCreditSequenceItemInputRepresentation> paymentCreditSequenceItems;
	global List<ConnectApi.RefundSequenceItemInputRepresentation> refundSequenceItems;
	global RefundInstructionsHintInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}