global class RefundInstructionsHintOutputRepresentation {
	global List<ConnectApi.PaymentCreditSequenceItemOutputRepresentation> paymentCreditSequence;
	global List<ConnectApi.RefundSequenceItemOutputRepresentation> refundSequence;
	global RefundInstructionsHintOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}