global class RejectedCustomerMergeAccount {
	global String errorMessage;
	global String losingExternalIdField;
	global String losingId;
	global String winningExternalIdField;
	global String winningId;
	global RejectedCustomerMergeAccount() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}