global class RemoteSessionConnectionOutput {
	global String connectionParams;
	global String errorMessage;
	global String errorMessageLabel;
	global ConnectApi.RemoteError remoteError;
	global String serviceProvider;
	global String status;
	global RemoteSessionConnectionOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}