global class RemoteSessionGetOutput {
	global String errorMessage;
	global String errorMessageLabel;
	global ConnectApi.RemoteError remoteError;
	global String status;
	global Boolean userAuthorized;
	global RemoteSessionGetOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}