global class RemoteSessionActionOutput {
	global String errorMessage;
	global String errorMessageLabel;
	global String linkExpirationTime;
	global String presignedURL;
	global String recordingLink;
	global ConnectApi.RemoteError remoteError;
	global String status;
	global String videoCallRecordingName;
	global RemoteSessionActionOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}