global class ResourceSlotsInputRep {
	global List<String> appointmentTypes;
	global String channelId;
	global String endDate;
	global List<ConnectApi.ResourceInputRep> resources;
	global List<String> serviceCategories;
	global List<String> serviceTypes;
	global String sourceSystem;
	global String startDate;
	global String workTypeId;
	global ResourceSlotsInputRep() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}