global class RestrictedPartyOutputListRepresentation {
	global List<ConnectApi.RestrictedPartyErrorOutputRepresentation> errorDetails;
	global Boolean isSuccess;
	global String message;
	global List<ConnectApi.RestrictedPartyOutputRepresentation> records;
	global RestrictedPartyOutputListRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}