global class RestrictedPartyOutputRepresentation {
	global Boolean isRestricted;
	global String participantRoleId;
	global String partyId;
	global String reason;
	global String reasonCategory;
	global RestrictedPartyOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}