global class RevenueScheduleRetrievalOutputRepresentation {
	global String error;
	global Boolean hasMoreRevenueSchedules;
	global Integer nextOffset;
	global List<ConnectApi.ScheduleDetailsOutputRepresentation> revenueScheduleDetailList;
	global String status;
	global RevenueScheduleRetrievalOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}