global class RevenueScheduleRetrievalInputRepresentation {
	global List<String> additionalFieldList;
	global ConnectApi.CalenderTypeEnum calendarType;
	global Integer offset;
	global String opportunityId;
	global Integer pageSize;
	global ConnectApi.RevenueSchedulePeriodTypeEnum periodType;
	global ConnectApi.RevenueScheduleViewTypeEnum type;
	global RevenueScheduleRetrievalInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}