global class RevenueScheduleProductOutputRepresentation {
	global Map<String,Object> additionalFields;
	global Double adjustedAmount;
	global Double billedAmount;
	global Double bookedAmount;
	global Double deliveredAmount;
	global String endDate;
	global String lastUpdatedDate;
	global Double plannedBudget;
	global String productName;
	global String startDate;
	global List<ConnectApi.TeamMemberOutputRepresentation> teamList;
	global RevenueScheduleProductOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}