global class RulesEvaluationResult {
	global String description;
	global List<String> failedRecordIds;
	global String message;
	global String ruleId;
	global String ruleName;
	global String severity;
	global String status;
	global RulesEvaluationResult() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}