global class SampleManagementOutputRepresentation {
	global ConnectApi.ProductRequirementSpecificationOutput data;
	global List<ConnectApi.ProductRequirementSpecificationErrorDetail> errors;
	global String message;
	global String requestUniqueId;
	global String status;
	global SampleManagementOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}