global class ScheduleDetailsOutputRepresentation {
	global String endDate;
	global String period;
	global List<ConnectApi.RevenueScheduleProductOutputRepresentation> productList;
	global String startDate;
	global ScheduleDetailsOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}