global class ScoringQueryResult {
	global ConnectApi.ScoringQueryAdditionalScores additionalScores;
	global String businessUnitId;
	global String businessUnitName;
	global Integer overallScore;
	global String scoringModelId;
	global String scoringModelName;
	global String unifiedRecordId;
	global ScoringQueryResult() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}