global class ScoringQueryWithRecordResult {
	global ConnectApi.ScoringQueryAdditionalScores additionalScores;
	global List<String> crmRecords;
	global Integer overallScore;
	global String unifiedRecordId;
	global ScoringQueryWithRecordResult() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}