global class ScoringQueryWithRecordResultList {
	global List<ConnectApi.ScoringQueryWithRecordResult> queryWithRecordResults;
	global String scoringModelId;
	global String scoringModelName;
	global ScoringQueryWithRecordResultList() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}