global class SequencesAssignmentResultOutputRepresentation {
	global List<ConnectApi.SequenceErrorOutputRepresentation> errors;
	global Boolean isSuccess;
	global String sequencePatternValue;
	global String sequencePolicyId;
	global String targetObjectId;
	global SequencesAssignmentResultOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}