global class SequencesAssignmentOutputRepresentation {
	global List<ConnectApi.SequenceErrorOutputRepresentation> errors;
	global List<ConnectApi.SequencesAssignmentResultOutputRepresentation> sequencesAssignment;
	global ConnectApi.SequenceResponseStatusEnum status;
	global SequencesAssignmentOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}