global class StatementOfAccountOutputRepresentation {
	global String accountId;
	global List<ConnectApi.ErrorResponse> errors;
	global String requestIdentifier;
	global String statusURL;
	global Boolean success;
	global String templateId;
	global StatementOfAccountOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}