global class SubjectRepresentation {
	global Map<String,String> additionalFields;
	global String deliveryMode;
	global String description;
	global String id;
	global String name;
	global String status;
	global String usageType;
	global SubjectRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}