global class UnfilledJobPositionShiftOutputRepresentation {
	global Integer capacityPercent;
	global String endDate;
	global String endTime;
	global String id;
	global String jobPositionName;
	global String jobPositionShiftName;
	global String jobPositionShiftStatus;
	global Integer maxAttendeesCount;
	global Integer positionAssignmentCount;
	global Integer remainingCapacity;
	global String startDate;
	global String startTime;
	global String timeZone;
	global UnfilledJobPositionShiftOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}