global class UnifiedSummaryConfiguration {
	global Datetime createdDate;
	global String developerName;
	global String id;
	global Boolean isActive;
	global String label;
	global Datetime lastModifiedDate;
	global String namespace;
	global String objectApiName;
	global String promptTemplateName;
	global UnifiedSummaryConfiguration() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}