global class UpdateClaimCoverageInputRep {
	global List<ConnectApi.ClaimAdditionalFieldInputRep> additionalFields;
	global String claimId;
	global String coverageId;
	global Double expenseReserveAmount;
	global Double lossReserveAmount;
	global UpdateClaimCoverageInputRep() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}