global class UseCaseTemplateMappingAttribute {
	global String alias;
	global String attributeId;
	global String defaultValue;
	global ConnectApi.UseCaseTemplateMappingAttributeFilterOption filterOptions;
	global List<ConnectApi.UseCaseTemplateMappingPathAttribute> path;
	global ConnectApi.UseCaseTemplateMappingSubjectAttribute subjectAttribute;
	global String tableName;
	global UseCaseTemplateMappingAttribute() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}