global class UseCaseTemplateAttributeConfigRepresentation {
	global String alias;
	global String defaultValue;
	global String description;
	global ConnectApi.UseCaseTemplateAttributeQueryOptionConfigRepresentation queryOptions;
	global Boolean required;
	global String tableName;
	global UseCaseTemplateAttributeConfigRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}