global class UseCaseTemplateAttributeQueryOptionConfigRepresentation {
	global ConnectApi.UseCaseTemplateAttributeAggregateConfigRepresentation aggregationOption;
	global Boolean selectable;
	global Boolean supportGroupBy;
	global Boolean supportJoin;
	global UseCaseTemplateAttributeQueryOptionConfigRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}