global class UseCaseTemplateMemberConfigRepresentation {
	global List<ConnectApi.UseCaseTemplateAttributeConfigRepresentation> attributeConfigs;
	global ConnectApi.DataCleanRoomMemberTypeEnum memberType;
	global UseCaseTemplateMemberConfigRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}