global class UseCaseTemplateMappingPathAttribute {
	global ConnectApi.UseCaseTemplateMappingSubjectAttribute sourceAttribute;
	global ConnectApi.UseCaseTemplateMappingSubjectAttribute targetAttribute;
	global UseCaseTemplateMappingPathAttribute() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}