global class UseCaseTemplateAttributeAggregateConfigRepresentation {
	global List<ConnectApi.UseCaseTemplateAttributeAggregateFunctionTypeEnum> operators;
	global Integer threshold;
	global UseCaseTemplateAttributeAggregateConfigRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}