global class ValueMap {
	global Datetime createdAt;
	global String defaultValue;
	global String defaultValueStrategy;
	global String description;
	global String id;
	global String label;
	global String name;
	global String sourceType;
	global String targetType;
	global Datetime updatedAt;
	global List<ConnectApi.InteractionValueMapEntry> valueMapEntries;
	global ValueMap() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}