global class VoidPostedCreditMemoOutputRepresentation {
	global String debitMemoId;
	global List<ConnectApi.ErrorResponse> errors;
	global Boolean isSuccess;
	global String statusURL;
	global VoidPostedCreditMemoOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}