global class VolunteerMatchingAccountsRep {
	global String errorMessage;
	global List<String> jobPositionShifts;
	global List<String> locations;
	global List<ConnectApi.MatchingAccountRep> matchingAccountRecords;
	global String orderBy;
	global List<String> qualifications;
	global List<String> timeRanges;
	global VolunteerMatchingAccountsRep() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}