global class WhatsappBusinessAccountFlowDetail {
	global ConnectApi.WhatsappBusinessAccountFlow flow;
	global List<ConnectApi.WhatsappBusinessAccountFlowAsset> flowAssets;
	global String jsonVersion;
	global ConnectApi.WhatsappBusinessAccountFlowPreview preview;
	global String status;
	global WhatsappBusinessAccountFlowDetail() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}