global class BankPaymentMethodResponse {
	global BankPaymentMethodResponse() { }
	global Object clone() { }
	global void setAccountHolderType(commercepayments.AccountHolderType accountHolderType) { }
	global void setAccountId(String accountId) { }
	global void setAccountType(commercepayments.AccountType accountType) { }
	global void setBankCode(String bankCode) { }
	global void setBankName(String bankName) { }
	global void setBankType(commercepayments.BankType bankType) { }
	global void setComments(String comments) { }
	global void setEmail(String email) { }
	global void setGatewayToken(String gatewayToken) { }
	global void setGatewayTokenDetails(String gatewayTokenDetails) { }
	global void setLast4(String lastFour) { }
	global void setName(String name) { }
	global void setSavedPaymentMethodId(String savedPaymentMethodId) { }
	global void setStandardEntryClassCode(commercepayments.StandardEntryClassCode standardEntryClassCode) { }

}