global class PaymentMethodTokenizationResponse {
	global PaymentMethodTokenizationResponse() { }
	global Object clone() { }
	global void setAmount(Double amount) { }
	global void setAsync(Boolean async) { }
	global void setBankName(String bankName) { }
	global void setChecksum(String checksum) { }
	global void setCustomerReference(String customerReference) { }
	global void setGatewayAvsCode(String gatewayAvsCode) { }
	global void setGatewayDate(Datetime gatewayDate) { }
	global void setGatewayMessage(String gatewayMessage) { }
	global void setGatewayReferenceDetails(String gatewayReferenceDetails) { }
	global void setGatewayReferenceNumber(String gatewayReferenceNumber) { }
	global void setGatewayResultCode(String gatewayResultCode) { }
	global void setGatewayResultCodeDescription(String gatewayResultCodeDescription) { }
	global void setGatewayToken(String gatewayToken) { }
	global void setGatewayTokenDetails(String gatewayTokenDetails) { }
	global void setGatewayTokenEncrypted(String gatewayTokenEncrypted) { }
	global void setRetryCategory(commercepayments.RetryCategory retryCategory) { }
	global void setRetryDecision(commercepayments.RetryDecision retryDecision) { }
	global void setSalesforceResultCodeInfo(commercepayments.SalesforceResultCodeInfo salesforceResultCodeInfo) { }

}